name: hitung_kalori_micoco
description: "Aplikasi pelacak kalori, nutrisi, barcode scanner, dan AI food analysis."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Navigation & UI
  google_fonts: ^6.1.0
  flutter_spinkit: ^5.2.0
  fl_chart: ^0.66.0
  percent_indicator: ^4.2.3

  # Authentication & Database
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.2

  # Monetization (RevenueCat & AdMob)
  purchases_flutter: ^8.1.0
  google_mobile_ads: ^5.0.0

  # Camera & AI / Barcode Scanner
  mobile_scanner: ^5.0.0
  image_picker: ^1.0.7
  google_generative_ai: ^0.2.2

  # Networking & Utilities
  http: ^1.2.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
