allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

subprojects {
    project.evaluationDependsOn(":app")
}

// Memastikan semua plugin eksternal (termasuk purchases_flutter) mendapatkan konfig Android
subprojects {
    afterEvaluate { subproject ->
        if (subproject.hasProperty('android')) {
            subproject.android {
                if (namespace == null) {
                    namespace subproject.group
                }
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
